apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: heag4ywmm-go 
  janus-idp.io/tekton: heag4ywmm-go
  backstage.io/kubernetes-id: heag4ywmm-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: heag4ywmm-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml